apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-moments-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "瞬间"
    rbac.authorization.halo.run/display-name: "瞬间查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:moments:view"]
rules:
  - apiGroups: ["moment.halo.run"]
    resources: ["moments"]
    verbs: ["get", "list"]
  - apiGroups: ["console.api.moment.halo.run"]
    resources: ["moments", "tags"]
    verbs: ["get", "list"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-moments-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "瞬间"
    rbac.authorization.halo.run/display-name: "瞬间管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:moments:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-moments-view"]
rules:
  - apiGroups: ["moment.halo.run"]
    resources: ["moments"]
    verbs: ["create", "patch", "update", "delete", "deletecollection"]
  - apiGroups: ["console.api.moment.halo.run"]
    resources: ["moments", "tags"]
    verbs: ["create", "patch", "update", "delete", "deletecollection"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-uc-moments-publish
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "瞬间"
    rbac.authorization.halo.run/display-name: "允许发布自己的瞬间"
    rbac.authorization.halo.run/ui-permissions: |
      ["uc:plugin:moments:publish"]
rules:
  - apiGroups: ["uc.api.moment.halo.run"]
    resources: ["moments", "tags"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-uc-moments-approved
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "瞬间"
    rbac.authorization.halo.run/display-name: "发布瞬间无需审核"
    rbac.authorization.halo.run/dependencies: |
      ["role-template-uc-moments-publish"]
rules:
  - nonResourceURLs: ["*"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-uc-moments-delete
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "瞬间"
    rbac.authorization.halo.run/display-name: "允许删除自己的瞬间"
    rbac.authorization.halo.run/ui-permissions: |
      ["uc:plugin:moments:delete"]
rules:
  - apiGroups: ["uc.api.moment.halo.run"]
    resources: ["moments", "tags"]
    verbs: ["delete", "deletecollection"]
